name: Deploy Backend TCM to VPS

on:
  push:
    branches:
      - master   # atau 'main' kalau branch kamu bukan master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no bambang@202.10.40.134 "cd ~/ToolCoolantMngmt_BackEnd && ./deploy.sh"

