name: Deploy Backend to VPS

on:
  push:
    branches:
      - main  # Ganti sesuai branch yang kamu pakai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Test SSH to VPS (verbose)
        run: |
          ssh -vvv -p 2025 -o StrictHostKeyChecking=no bambang@202.10.40.134 "echo 'SSH connection works!'"

      - name: Deploy to VPS
        if: success()  # Hanya jalan kalau step test SSH berhasil
        run: |
          ssh -p 2025 -o StrictHostKeyChecking=no bambang@202.10.40.134 "cd ~/ToolCoolantMngmt_BackEnd && ./deploy.sh"
